AWSTemplateFormatVersion: "2010-09-09"
Description: Sample CloudFormation template for an S3 bucket

Resources:
  SampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: inframind-ai-sample-cfn-yaml
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: Name of the created bucket
    Value: !Ref SampleBucket