export const mockData = {
  stats: [
    { label: "Total Analyses", value: 47, icon: "FileText" },
    { label: "Issues Found", value: 143, icon: "AlertCircle" },
    { label: "Cost Savings", value: "$12,450", icon: "DollarSign" },
    { label: "Security Score", value: "94%", icon: "Shield" },
  ],
  recentAnalyses: [
    {
      id: "1",
      name: "Production Infrastructure",
      date: "2024-05-05",
      status: "completed",
      issuesFound: 12,
      severity: "high",
    },
    {
      id: "2",
      name: "Staging Environment",
      date: "2024-05-04",
      status: "completed",
      issuesFound: 5,
      severity: "medium",
    },
    {
      id: "3",
      name: "Development Cluster",
      date: "2024-05-03",
      status: "completed",
      issuesFound: 8,
      severity: "medium",
    },
    {
      id: "4",
      name: "Database Infrastructure",
      date: "2024-05-02",
      status: "analyzing",
      issuesFound: 0,
      severity: "low",
    },
  ],
  issues: [
    {
      id: "1",
      title: "Unencrypted S3 Bucket",
      description: "S3 bucket 'prod-data' is not using server-side encryption",
      severity: "critical" as const,
      category: "security",
      recommendation: "Enable default encryption on the S3 bucket",
      estimatedCost: "$0",
    },
    {
      id: "2",
      title: "Overly Permissive Security Group",
      description: "Security group allows ingress from 0.0.0.0/0 on port 3306",
      severity: "high" as const,
      category: "security",
      recommendation: "Restrict access to specific IP ranges",
      estimatedCost: "$0",
    },
    {
      id: "3",
      title: "Unused RDS Instance",
      description: "Database instance 'staging-db' has not been accessed in 30 days",
      severity: "medium" as const,
      category: "cost",
      recommendation: "Delete unused instance or resize to smaller capacity",
      estimatedCost: "$450/month",
    },
    {
      id: "4",
      title: "Missing Load Balancer Logging",
      description: "Application Load Balancer is not logging requests",
      severity: "high" as const,
      category: "security",
      recommendation: "Enable ALB access logging to S3",
      estimatedCost: "$10/month",
    },
    {
      id: "5",
      title: "High Disk Utilization",
      description: "EC2 instance i-0123456789abcdef0 disk at 92% capacity",
      severity: "medium" as const,
      category: "performance",
      recommendation: "Scale storage or archive old data",
      estimatedCost: "$20/month",
    },
    {
      id: "6",
      title: "Missing Backup Configuration",
      description: "RDS instance does not have automated backups enabled",
      severity: "high" as const,
      category: "security",
      recommendation: "Enable automated backups with 30-day retention",
      estimatedCost: "$0",
    },
  ],
  summary: {
    critical: 1,
    high: 3,
    medium: 2,
    low: 0,
  },
}
